# Generated by Django 2.2.7 on 2020-07-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExperienceSocket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('questions', models.ManyToManyField(to='ExperienceSocket.Question')),
            ],
        ),
    ]
