# Generated by Django 2.2.7 on 2020-07-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExperienceSocket', '0004_surveyquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('single', 'Single Survey'), ('interval', 'Interval Survey')], default='single', help_text='Je nach Typ ist das Scheduling in Intervallen (exklusiv Start & End!) oder einmalig.', max_length=15),
        ),
    ]
